name: Gem Workflow
on: [push, pull_request]
jobs:
  rubocop:
    strategy:
      matrix:
        ruby-version: [2.6.3, 2.6.6, 2.7.1, head]
    runs-on: [ubuntu-latest]
    continue-on-error: ${{ matrix.ruby-version == 'head'}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Ruby Setup and Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rubocop
  rspec:
    strategy:
      matrix:
        ruby-version: [2.6.3, 2.6.6, 2.7.1, head]
    runs-on: [ubuntu-latest]
    continue-on-error: ${{ matrix.ruby-version == 'head'}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Ruby Setup and Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rspec --order rand
  publish:
    runs-on: ubuntu-latest
    needs: ['rubocop', 'rspec']
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Ruby Setup and Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{ secrets.RUBY_GEM_KEY }}"